# config is file op-geth/cmd/geth/config.go  gethConfig
[Eth]
NetworkId = 242070
RollupDisableTxPoolGossip = true
SyncMode = "full"

[Node]
DataDir = "./datadir"
HTTPHost = "0.0.0.0"
HTTPPort = 8515
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "debug", "eth", "txpool", "net", "engine", "admin"]
WSHost = "0.0.0.0"
WSPort = 8516
WSOrigins = ["*"]
WSModules = ["debug", "eth", "txpool", "net", "engine"]
AuthVirtualHosts = ["*"]
AuthAddr = "0.0.0.0"
AuthPort = 8521
JWTSecret = "./jwt.txt"

[Node.P2P]
ListenAddr = ":8503"
NetRestrict = ["172.31.0.0/16"]
